#!/usr/bin/env node
/**
 * This script reads all 6 screenshots and generates the Figma plugin code.js
 * with the screenshots embedded as base64 strings.
 *
 * Run: node generate-plugin.mjs
 * Output: figma-plugin/code.js  (and figma-plugin/manifest.json + ui.html)
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve } from "node:path";

const SCREENSHOTS_DIR = "/Users/m4/.gemini/antigravity/brain/c6542d0c-002f-4393-8a17-20aab3c3b8a6";

const SCREENS = [
  { name: "Home", file: "home_1771731462021.png" },
  { name: "SMC Viewer – Chart", file: "smc_viewer_1771731470308.png" },
  { name: "Engine 2 – Reference", file: "engine2_reference_1771731477554.png" },
  { name: "Engine 2 – Diagnostics", file: "engine2_diagnostics_1771731484039.png" },
  { name: "Engine 2 – Evaluate (Checklist)", file: "engine2_evaluate_1771731490672.png" },
  { name: "Engine 2 – Tune", file: "engine2_tune_1771731497254.png" },
];

console.log("Reading screenshots...");
const screensWithData = SCREENS.map((s) => {
  const imgPath = resolve(SCREENSHOTS_DIR, s.file);
  const bytes = readFileSync(imgPath);
  const b64 = bytes.toString("base64");
  console.log(`  ${s.name}: ${Math.round(bytes.length / 1024)} KB → ${Math.round(b64.length / 1024)} KB base64`);
  return { name: s.name, base64: b64 };
});

mkdirSync("figma-plugin", { recursive: true });

// ─── manifest.json ─────────────────────────────────────────────────────────
const manifest = {
  name: "SMC Viewer Designs Importer",
  id: "smc-viewer-designs-importer",
  api: "1.0.0",
  main: "code.js",
  ui: "ui.html",
  editorType: ["figma"],
};
writeFileSync("figma-plugin/manifest.json", JSON.stringify(manifest, null, 2));

// ─── ui.html ───────────────────────────────────────────────────────────────
const uiHtml = `<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Inter, sans-serif; padding: 20px; background: #1a1a1a; color: #e0e0e0; margin: 0; }
    h2 { margin: 0 0 8px; font-size: 16px; }
    p { font-size: 12px; color: #888; margin: 0 0 16px; }
    button {
      background: #18a0fb; color: #fff; border: none; border-radius: 6px;
      padding: 10px 20px; font-size: 14px; cursor: pointer; width: 100%;
    }
    button:hover { background: #0d8de8; }
    #status { margin-top: 12px; font-size: 12px; color: #aaa; min-height: 20px; }
  </style>
</head>
<body>
  <h2>SMC Viewer Designs Importer</h2>
  <p>Creates 6 frames (1440×900) in a new Figma page with screenshots from the SMC Viewer app.</p>
  <button id="run">Create Design Frames</button>
  <div id="status"></div>
  <script>
    document.getElementById('run').onclick = function() {
      this.disabled = true;
      document.getElementById('status').textContent = 'Creating frames…';
      parent.postMessage({ pluginMessage: { type: 'create-frames' } }, '*');
    };
    window.onmessage = function(e) {
      const msg = e.data.pluginMessage;
      if (!msg) return;
      if (msg.type === 'progress') {
        document.getElementById('status').textContent = msg.text;
      } else if (msg.type === 'done') {
        document.getElementById('status').textContent = '✅ Done! ' + msg.count + ' frames created.';
        document.getElementById('run').disabled = false;
      } else if (msg.type === 'error') {
        document.getElementById('status').textContent = '❌ Error: ' + msg.message;
        document.getElementById('run').disabled = false;
      }
    };
  </script>
</body>
</html>`;
writeFileSync("figma-plugin/ui.html", uiHtml);

// ─── code.js (plugin main thread) ─────────────────────────────────────────
const screensJson = JSON.stringify(screensWithData.map((s) => ({ name: s.name, base64: s.base64 })));

const codeJs = `// SMC Viewer Designs Importer — Figma Plugin
// Auto-generated by generate-plugin.mjs
// Paste this into Figma → Plugins → Development → Create new plugin (or use manifest.json)

const FRAME_WIDTH = 1440;
const FRAME_HEIGHT = 900;
const FRAME_GAP = 120;

const SCREENS = ${screensJson};

// Pure-JS base64 decoder — atob() is NOT available in the Figma plugin main thread
function base64ToUint8Array(base64) {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
  const lookup = new Uint8Array(256);
  for (let i = 0; i < chars.length; i++) lookup[chars.charCodeAt(i)] = i;

  const clean = base64.replace(/[=]+$/, '');
  const outLen = Math.floor(clean.length * 3 / 4);
  const out = new Uint8Array(outLen);
  let i = 0, j = 0;
  while (i < clean.length) {
    const b0 = lookup[clean.charCodeAt(i++)];
    const b1 = lookup[clean.charCodeAt(i++)];
    const b2 = i <= clean.length ? lookup[clean.charCodeAt(i++)] : 0;
    const b3 = i <= clean.length ? lookup[clean.charCodeAt(i++)] : 0;
    out[j++] = (b0 << 2) | (b1 >> 4);
    if (j < outLen) out[j++] = ((b1 & 0xf) << 4) | (b2 >> 2);
    if (j < outLen) out[j++] = ((b2 & 0x3) << 6) | b3;
  }
  return out;
}

figma.showUI(__html__, { width: 340, height: 160 });

figma.ui.onmessage = async function(msg) {
  if (msg.type !== 'create-frames') return;

  try {
    // Create a new page for the designs
    const page = figma.createPage();
    page.name = 'SMC Viewer Designs';
    // setCurrentPageAsync not available in API 1.0.0 — use direct assignment
    figma.currentPage = page;

    for (let i = 0; i < SCREENS.length; i++) {
      const screen = SCREENS[i];
      figma.ui.postMessage({ type: 'progress', text: 'Creating: ' + screen.name + ' (' + (i + 1) + '/' + SCREENS.length + ')…' });

      // Decode base64 PNG to bytes
      const bytes = base64ToUint8Array(screen.base64);

      // Create image via Plugin API
      const image = figma.createImage(bytes);

      // Create a top-level frame
      const frame = figma.createFrame();
      frame.name = screen.name;
      frame.resize(FRAME_WIDTH, FRAME_HEIGHT);
      frame.x = i * (FRAME_WIDTH + FRAME_GAP);
      frame.y = 0;
      frame.fills = [];
      frame.clipsContent = true;
      
      // Add a rectangle inside the frame with the image fill
      const rect = figma.createRectangle();
      rect.name = 'Screenshot';
      rect.resize(FRAME_WIDTH, FRAME_HEIGHT);
      rect.x = 0;
      rect.y = 0;
      rect.fills = [{
        type: 'IMAGE',
        scaleMode: 'FILL',
        imageHash: image.hash,
      }];

      frame.appendChild(rect);
      page.appendChild(frame);

      // Allow UI to update between frames
      await new Promise(r => setTimeout(r, 10));
    }

    // Zoom to fit all frames
    figma.viewport.scrollAndZoomIntoView(page.children);

    figma.ui.postMessage({ type: 'done', count: SCREENS.length });
  } catch (err) {
    figma.ui.postMessage({ type: 'error', message: err.message || String(err) });
  }
};
`;

writeFileSync("figma-plugin/code.js", codeJs);

console.log("\n✅ Figma plugin generated in ./figma-plugin/");
console.log("   Files:");
console.log("   - figma-plugin/manifest.json");
console.log("   - figma-plugin/code.js  (", Math.round(codeJs.length / 1024), "KB)");
console.log("   - figma-plugin/ui.html");
console.log("\nNext steps:");
console.log("  1. Open Figma Desktop");
console.log("  2. Menu → Plugins → Development → Import plugin from manifest...");
console.log("  3. Select: figma-plugin/manifest.json");
console.log("  4. Run the plugin → click 'Create Design Frames'");
